# 第 1 幕（Day 1-10）：九月初，搬家到海景镇。语法：be 动词、there be、祈使句、介词、人称代词。
DAYS = [
    dict(day=1, act=1, theme="搬家日：抵达新家",
         sent=["a, an", "be", "the", "and", "in", "on", "I", "we", "our", "new", "home", "house", "town", "there"],
         ext=[("房屋与院落（锚词：house）", "house", ["garden", "gate", "wall"])]),
    dict(day=2, act=1, theme="看新家：there be 数房间",
         sent=["have", "have got", "here", "room", "door", "window", "floor", "bedroom", "kitchen", "big", "small", "it", "you", "your", "this"],
         ext=[("更多房间（锚词：room）", "room", ["bathroom", "toilet", "hall"])]),
    dict(day=3, act=1, theme="家庭成员",
         sent=["family", "father", "mother", "brother", "sister", "baby", "parent", "son", "they", "he", "she"],
         ext=[("家庭称呼（锚词：father）", "father", ["dad", "mummy", "grandpa", "grandma"]),
              ("女儿与姑姨（锚词：sister）", "sister", ["daughter", "aunt"])]),
    dict(day=4, act=1, theme="搬家具",
         sent=["furniture", "table", "chair", "desk", "bed", "sofa", "lamp", "clock", "fridge", "cupboard", "my", "me"],
         ext=[("收纳与床品（锚词：bed）", "bed", ["bookshelf", "shelf", "pillow", "blanket"])]),
    dict(day=5, act=1, theme="整理箱子",
         sent=["box", "bag", "put", "carry", "open", "close", "thing", "heavy", "empty", "with", "for", "from"],
         ext=[("随身小物（锚词：bag）", "bag", ["wallet", "purse", "key"])]),
    dict(day=6, act=1, theme="镇上初探",
         sent=["shop", "supermarket", "park", "road", "bridge", "river", "hill", "place", "near", "old", "us"],
         ext=[("更多场所（锚词：shop）", "shop", ["market", "bookshop"])]),
    dict(day=7, act=1, theme="拜访邻居",
         sent=["neighbour", "meet", "name", "nice", "welcome", "glad", "hello", "goodbye", "at", "to", "of", "Mr", "Mrs"],
         ext=[("礼貌用语（锚词：hello）", "hello", ["please", "thank", "sorry", "cheers", "pardon"])]),
    dict(day=8, act=1, theme="数新家：数字 1-10",
         sent=["three", "five", "eight", "boy", "girl", "dog", "cat", "age", "by", "not"],
         ext=[("基数词 1-10（锚词：five）", "five", ["one", "two", "four", "six", "seven", "nine", "ten"])]),
    dict(day=9, act=1, theme="数字 11-20",
         sent=["twelve", "fifteen", "twenty", "zero", "man", "woman", "child", "adult", "no"],
         ext=[("基数词 11-20（锚词：twelve）", "twelve",
               ["eleven", "thirteen", "fourteen", "sixteen", "seventeen", "eighteen", "nineteen"])]),
    dict(day=10, act=1, theme="买文具：颜色",
         sent=["colour", "red", "blue", "yellow", "schoolbag", "pen", "pencil", "ruler", "rubber", "sharpener"],
         ext=[("常见颜色（锚词：blue）", "blue", ["green", "black", "white", "grey", "pink", "purple"])]),
]
