# 第 6 幕（Day 51-60）：十一月，冷与暖。语法：一般过去时核心、will 预告。
DAYS = [
    dict(day=51, act=6, theme="入冬与冰雪运动",
         sent=["winter", "ice", "snow", "snowy", "skate", "ski", "heating", "fire", "degree", "stormy"],
         ext=[("冬季运动（锚词：ski）", "ski", ["skiing", "ice skating", "skating", "snowboard", "snowboarding"]),
              ("风暴家族（锚词：stormy）", "stormy", ["thunderstorm", "temperature", "raincoat"])]),
    dict(day=52, act=6, theme="居家与洗浴",
         sent=["flat", "apartment", "stairs", "upstairs", "downstairs", "lift", "bath", "shower", "mirror", "curtains"],
         ext=[("洗漱用品（锚词：bath）", "bath", ["soap", "towel", "toothbrush", "shampoo"])]),
    dict(day=53, act=6, theme="厨房做饭",
         sent=["cook", "cooker", "bake", "boil", "fry", "grill", "roast", "cut", "dish", "wash up", "during"],
         ext=[("烹饪方式（锚词：fry）", "fry", ["fried", "grilled"])]),
    dict(day=54, act=6, theme="世界各地的食物",
         sent=["pasta", "pie", "pizza", "sausage", "steak", "chips", "fast food", "sandwich", "omelette", "pancake", "toast", "cereal"],
         ext=[]),
    dict(day=55, act=6, theme="去餐厅",
         sent=["restaurant", "menu", "order", "waiter", "waitress", "customer", "bill", "fork", "knife", "spoon", "plate", "bowl", "main course"],
         ext=[("餐具补充（锚词：plate）", "plate", ["cup", "glass", "bottle"])]),
    dict(day=56, act=6, theme="做家务",
         sent=["housework", "tidy", "tidy up", "clean", "cleaner", "wash", "help", "dirty", "husband", "wife", "single"],
         ext=[("清洁工具（锚词：clean）", "clean", ["brush", "comb"])]),
    dict(day=57, act=6, theme="邮局与银行",
         sent=["bank", "post office", "post", "postman", "postcard", "stamp", "envelope", "letter", "police", "police station", "will"],
         ext=[("警察家族（锚词：police）", "police", ["police officer", "police car"])]),
    dict(day=58, act=6, theme="城镇地标",
         sent=["fire station", "firefighter", "museum", "theatre", "cathedral", "castle", "church", "square", "stadium"],
         ext=[("文化场所（锚词：theatre）", "theatre", ["cinema", "disco", "exhibition"])]),
    dict(day=59, act=6, theme="职业与工作",
         sent=["job", "work", "worker", "occupation", "career", "boss", "manager", "secretary", "colleague", "businessman", "businesswoman"],
         ext=[("助理与店员（锚词：boss）", "boss", ["assistant", "shop assistant", "receptionist"])]),
    dict(day=60, act=6, theme="各行各业",
         sent=["nurse", "writer", "journalist", "photographer", "musician", "painter", "footballer", "tennis player", "engineer"],
         ext=[("手艺与服务（锚词：nurse）", "nurse", ["mechanic", "chemist", "hairdresser", "gardener", "guide", "tour guide"])]),
]
