# 第 2 幕（Day 11-20）：新学校第一周。语法：一般现在时、疑问句、疑问词。
DAYS = [
    dict(day=11, act=2, theme="开学第一天",
         sent=["school", "classroom", "class", "classmate", "teacher", "pupil", "lesson", "book", "notebook", "dictionary", "crayon", "scissors", "do"],
         ext=[("书籍与纸页（锚词：book）", "book", ["text book", "page", "diary"]),
              ("同班同学（锚词：classmate）", "classmate", ["class member"])]),
    dict(day=12, act=2, theme="科目表",
         sent=["subject", "mathematics", "science", "geography", "history", "art", "music", "Chinese", "difficult", "easy", "favourite"],
         ext=[("学期与课程（锚词：subject）", "subject", ["term", "course", "studies"])]),
    dict(day=13, act=2, theme="每日作息",
         sent=["go", "get", "get up", "up", "morning", "breakfast", "eat", "hungry", "thirsty", "down", "out", "but"],
         ext=[("一日三餐（锚词：breakfast）", "breakfast", ["lunch", "dinner", "supper", "meal"])]),
    dict(day=14, act=2, theme="疑问词大扫除",
         sent=["what", "where", "when", "who", "whose", "which", "how", "why", "question", "answer"],
         ext=[("any- 不定代词（锚词：who）", "who", ["anybody", "anyone", "anything", "anywhere"]),
              ("some- 不定代词（锚词：who）", "who", ["somebody", "someone", "something", "somewhere"])]),
    dict(day=15, act=2, theme="星期与周末",
         sent=["Monday", "Friday", "week", "weekend", "weekday", "today", "now", "then", "daily", "after", "before"],
         ext=[("星期名（锚词：Monday）", "Monday", ["Tuesday", "Wednesday", "Thursday", "Saturday", "Sunday"])]),
    dict(day=16, act=2, theme="月份与生日",
         sent=["September", "October", "month", "date", "year", "birthday", "soon", "yesterday"],
         ext=[("月份名（锚词：September）", "September",
               ["January", "February", "March", "April", "May", "June", "July", "August", "November", "December"])]),
    dict(day=17, act=2, theme="频率副词",
         sent=["always", "usually", "often", "sometimes", "never", "every", "each", "all", "both", "many", "much", "few", "very", "too", "so"],
         ext=[("数量词（锚词：many）", "many", ["lot", "lots", "little"])]),
    dict(day=18, act=2, theme="不定代词与代词收尾",
         sent=["everybody", "everyone", "everything", "everywhere", "nobody", "no one", "nothing", "none", "nowhere", "them", "him", "their"],
         ext=[("物主代词（锚词：their）", "their", ["mine", "yours", "hers", "ours", "theirs"])]),
    dict(day=19, act=2, theme="兴趣爱好",
         sent=["like", "love", "enjoy", "because", "hobby", "game", "play", "fun", "funny", "interesting", "boring", "cartoon", "doll", "toy", "kite"],
         ext=[]),
    dict(day=20, act=2, theme="学校场所",
         sent=["library", "playground", "gym", "office", "staff", "group", "project", "meeting", "computer", "internet", "online", "keyboard"],
         ext=[]),
]
