# 第 8 幕（Day 71-80）：圣诞假期与澳大利亚之旅（南半球夏天）。语法：比较级/最高级巩固、现在完成时、被动入门。
DAYS = [
    dict(day=71, act=8, theme="打包出发",
         sent=["suitcase", "luggage", "pack", "passport", "ticket", "hotel", "arrive", "stay", "trip", "journey", "travel", "return"],
         ext=[("旅人（锚词：travel）", "travel", ["visit", "visitor", "tourist", "tour"]),
              ("旅行服务（锚词：journey）", "journey", ["travel agent", "tourist information centre"])]),
    dict(day=72, act=8, theme="海滩与泳池",
         sent=["beach", "sea", "summer", "swimming pool", "swimming costume", "swimming", "pool", "umbrella", "wave", "surfboard", "surfing"],
         ext=[("水上运动（锚词：surfing）", "surfing", ["surfboarding", "windsurfing", "sailing", "sail"])]),
    dict(day=73, act=8, theme="雨林露营",
         sent=["camp", "campsite", "tent", "barbecue", "rainforest", "explore", "explorer", "adventure", "map", "guidebook", "guy"],
         ext=[("船与航行（锚词：map）", "map", ["boat", "ship"])]),
    dict(day=74, act=8, theme="在澳大利亚",
         sent=["Australia", "Australian", "foreign", "language", "speak", "tell", "say", "talk", "conversation", "sentence", "spell", "surname"],
         ext=[("姓名（锚词：surname）", "surname", ["first name"]),
              ("语言元素（锚词：language）", "language", ["article"])]),
    dict(day=75, act=8, theme="城镇与乡村",
         sent=["country", "city", "countryside", "village", "world", "area", "centre", "crowd", "crowded", "city centre"],
         ext=[("大洲（锚词：world）", "world", ["Africa", "Asia", "Europe", "North America", "South America", "Antarctica"])]),
    dict(day=76, act=8, theme="国家与国籍 1",
         sent=["China", "Japan", "Japanese", "India", "Indian", "Brazil", "Brazilian", "Mexico"],
         ext=[("国籍对应 1（锚词：Japan）", "Japan", ["Korean", "Italian", "Spanish", "French", "German"]),
              ("国家名 1（锚词：China）", "China", ["Korea", "Italy", "Spain", "France", "Germany"])]),
    dict(day=77, act=8, theme="国家与国籍 2",
         sent=["Britain", "British", "America", "American", "Canada", "Canadian", "Russia", "Ireland", "national", "nationality", "international", "popular", "Mexican"],
         ext=[("国籍对应 2（锚词：Britain）", "Britain", ["Irish", "Russian"])]),
    dict(day=78, act=8, theme="电子设备",
         sent=["email", "message", "text", "text message", "phone", "telephone", "screen", "click", "download", "website", "laptop"],
         ext=[("设备（锚词：laptop）", "laptop", ["mobile phone", "printer", "digital", "hairdryer"])]),
    dict(day=79, act=8, theme="媒体与资讯",
         sent=["television", "TV", "radio", "video", "DVD", "channel", "programme", "film", "newsagent", "advertisement", "magazine", "news"],
         ext=[("播放设备（锚词：DVD）", "DVD", ["DVD player", "CD player", "MP3 player", "video recorder"]),
              ("纸媒与招贴（锚词：programme）", "programme", ["newspaper", "poster"])]),
    dict(day=80, act=8, theme="澳洲美食",
         sent=["burger", "cream", "lemonade", "mineral water", "slice", "snack", "delicious", "piece", "piece of cake", "tomato", "picnic", "kind", "fresh"],
         ext=[("户内户外（锚词：picnic）", "picnic", ["outdoor", "outdoors", "indoor", "indoors"])]),
]
