# 第 7 幕（Day 61-70）：十二月，圣诞与新年。语法：将来时 will、比较级入门、现在完成时入门。
DAYS = [
    dict(day=61, act=7, theme="圣诞节",
         sent=["Christmas", "New Year", "festival", "wishes", "card", "star", "lights", "member", "give", "congratulations", "sincerely"],
         ext=[("节日与庆典（锚词：Christmas）", "Christmas", ["Easter", "wedding"]),
              ("贺卡用语（锚词：card）", "card", ["dear"])]),
    dict(day=62, act=7, theme="祖孙同堂",
         sent=["grandfather", "grandmother", "grandparent", "grandson", "granddaughter", "grandchild", "granddad", "uncle", "cousin", "nephew", "niece", "guy"],
         ext=[("亲属总称（锚词：cousin）", "cousin", ["person", "people"]),
              ("婚姻（锚词：grandmother）", "grandmother", ["married"])]),
    dict(day=63, act=7, theme="音乐会",
         sent=["band", "concert", "drum", "guitar", "piano", "violin", "song", "pop", "rock", "jazz", "classical", "fan"],
         ext=[("音乐流派（锚词：jazz）", "jazz", ["hip hop", "rap", "reggae", "opera"]),
              ("乐器与载体（锚词：guitar）", "guitar", ["instrument", "CD"])]),
    dict(day=64, act=7, theme="比较级上线",
         sent=["than", "more", "most", "better", "less", "high", "low", "large", "narrow", "wide"],
         ext=[("程度副词（锚词：more）", "more", ["quite", "rather"]),
              ("反义复习（锚词：less）", "less",
               [{"rev": "small", "from": 2}, {"rev": "tall", "from": 50}, {"rev": "short", "from": 50},
                {"rev": "easy", "from": 12}, {"rev": "difficult", "from": 12}])]),
    dict(day=65, act=7, theme="制定计划",
         sent=["plan", "shall", "suppose", "maybe", "perhaps", "immediately", "possible", "impossible", "sure", "of course", "appointment", "cafe", "call", "fine", "far"],
         ext=[("预约地址（锚词：appointment）", "appointment", ["address"]),
              ("肯定与确定（锚词：sure）", "sure", ["certainly"])]),
    dict(day=66, act=7, theme="现在完成时入门",
         sent=["ever", "already", "yet", "since", "still", "happen", "leave", "return", "find", "begin", "die", "dead", "learn", "come"],
         ext=[("生命阶段（锚词：die）", "die", ["born", "life", "live"])]),
    dict(day=67, act=7, theme="动手动词",
         sent=["pull", "push", "hold", "check", "choose", "collect", "fill", "fix", "together", "only", "even", "point", "use"],
         ext=[("拥有与借还（锚词：hold）", "hold", ["own", "borrow", "belong"]),
              ("短语动词（锚词：fill）", "fill", ["fill in"])]),
    dict(day=68, act=7, theme="赞不绝口",
         sent=["amazing", "brilliant", "excellent", "fantastic", "wonderful", "perfect", "pleasant", "lovely", "great", "real", "really", "pretty"],
         ext=[("好极了复习（锚词：brilliant）", "brilliant",
               [{"rev": "nice", "from": 7}, {"rev": "good", "from": 50}, {"rev": "beautiful", "from": 50}])]),
    dict(day=69, act=7, theme="品质形容词",
         sent=["important", "clear", "clever", "correct", "wrong", "simple", "normal", "interested", "famous", "fair", "healthy", "free", "modern"],
         ext=[("平常与通常（锚词：normal）", "normal", ["usual"]),
              ("正确复习（锚词：correct）", "correct", [{"rev": "right", "from": 40}])]),
    dict(day=70, act=7, theme="意外与麻烦",
         sent=["accident", "ambulance", "insurance", "problem", "trouble", "danger", "dangerous", "safe", "save", "repair", "break", "change", "pity"],
         ext=[("延误（锚词：accident）", "accident", ["delay", "delayed"])]),
]
