# 第 5 幕（Day 41-50）：十月底-十一月，运动会与万圣节。语法：一般过去时上线、时间表达。
DAYS = [
    dict(day=41, act=5, theme="出行方位",
         sent=["into", "inside", "outside", "opposite", "next to", "in front of", "around", "straight on", "turn", "cross", "corner", "roundabout", "street", "straight"],
         ext=[("接近类（锚词：next to）", "next to", ["close to"]),
              ("路口设施（锚词：cross）", "cross", ["crossing", "crossroads"])]),
    dict(day=42, act=5, theme="日常交通工具",
         sent=["bus", "bus stop", "bus station", "taxi", "car", "car park", "bicycle", "bike", "drive", "driver", "traffic"],
         ext=[("道路车辆（锚词：car）", "car", ["lorry", "van", "motorbike"])]),
    dict(day=43, act=5, theme="长途与飞行",
         sent=["train", "railway", "railway station", "platform", "station", "tram", "underground", "coach", "plane", "aeroplane", "airport"],
         ext=[("飞行相关（锚词：plane）", "plane", ["flight", "helicopter", "pilot"])]),
    dict(day=44, act=5, theme="身体部位",
         sent=["body", "head", "hair", "eye", "ear", "nose", "mouth", "face", "tooth", "neck", "hand", "finger"],
         ext=[("身体收尾（锚词：body）", "body", ["thumb", "toe", "back", "arm", "leg", "knee"])]),
    dict(day=45, act=5, theme="生病与就医",
         sent=["ill", "sick", "fever", "cough", "headache", "pain", "hurt", "medicine", "dentist", "doctor"],
         ext=[("医疗场所（锚词：doctor）", "doctor", ["hospital", "pharmacy"])]),
    dict(day=46, act=5, theme="运动会（过去时上线）",
         sent=["ago", "last", "race", "score", "goal", "win", "winner", "take", "bring", "competition", "excited"],
         ext=[("输赢反义（锚词：win）", "win", ["lose"])]),
    dict(day=47, act=5, theme="万圣节派对",
         sent=["Halloween", "costume", "dark", "afraid", "party", "surprise", "special", "shout", "terrible", "strange"],
         ext=[("派对相关（锚词：party）", "party", ["guest", "present", "invite"])]),
    dict(day=48, act=5, theme="情绪表达",
         sent=["happy", "sad", "angry", "surprised", "bored", "tired", "alone", "feel", "cry", "hate", "worry", "miss"],
         ext=[("un- 反义前缀（锚词：happy）", "happy", ["unhappy"])]),
    dict(day=49, act=5, theme="想法与记忆",
         sent=["think", "know", "believe", "hope", "wish", "want", "need", "remember", "forget", "decide", "mean", "understand"],
         ext=[("想法名词（锚词：think）", "think", ["idea"])]),
    dict(day=50, act=5, theme="形容词反义对",
         sent=["tall", "short", "long", "good", "bad", "beautiful", "ugly", "strong", "weak", "fat", "thin", "young"],
         ext=[("反义形容词复习（锚词：tall）", "tall",
               [{"rev": "big", "from": 2}, {"rev": "small", "from": 2}, {"rev": "old", "from": 6},
                {"rev": "hot", "from": 32}, {"rev": "cold", "from": 32}])]),
]
