# 第 4 幕（Day 31-40）：十月·秋天。语法：must/have to 深化、否定、祈使句。
# 本幕包含数字大单位与序数词的集中分配（借助价格、日期场景）。
DAYS = [
    dict(day=31, act=4, theme="秋天的景色",
         sent=["autumn", "wind", "windy", "sky", "fall", "tree", "wood", "forest", "grass", "field", "flower", "plant", "grow"],
         ext=[("云家族（锚词：wind）", "wind", ["cloud", "cloudy"])]),
    dict(day=32, act=4, theme="天气怎么样",
         sent=["weather", "rain", "rainy", "sun", "sunny", "warm", "cool", "hot", "cold", "dry", "wet"],
         ext=[("天气补充（锚词：rain）", "rain", ["storm", "fog", "foggy", "rainbow"])]),
    dict(day=33, act=4, theme="秋季衣橱",
         sent=["clothes", "T-shirt", "jeans", "sweater", "jacket", "coat", "shirt", "skirt", "dress", "blouse", "suit", "tie"],
         ext=[("下装（锚词：jeans）", "jeans", ["trousers", "shorts", "tights"])]),
    dict(day=34, act=4, theme="鞋帽与穿戴",
         sent=["wear", "put on", "try on", "shoes", "boots", "sock", "hat", "cap", "scarf", "gloves"],
         ext=[("配饰（锚词：hat）", "hat", ["belt", "glasses"])]),
    dict(day=35, act=4, theme="逛街购物",
         sent=["shopping", "buy", "sell", "price", "cost", "pay", "money", "cheap", "expensive", "discount", "size", "spend"],
         ext=[("促销相关（锚词：price）", "price", ["sale", "for sale"])]),
    dict(day=36, act=4, theme="钱币与价格",
         sent=["pound", "dollar", "euro", "penny", "pence", "cent", "cash", "credit card", "cheque", "fifty", "hundred"],
         ext=[("整十数（锚词：fifty）", "fifty", ["thirty", "forty", "sixty", "seventy", "eighty", "ninety"])]),
    dict(day=37, act=4, theme="数字大单位与序数开头",
         sent=["thousand", "million", "dozen", "double", "first", "third", "number", "whole", "enough", "certain"],
         ext=[("序数词 4-10（锚词：third）", "third", ["fourth", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth"])]),
    dict(day=38, act=4, theme="日期里的序数",
         sent=["eleventh", "twelfth", "twentieth", "several", "once", "twice", "again", "just"],
         ext=[("序数 13-19（锚词：twelfth）", "twelfth",
               ["thirteenth", "fourteenth", "fifteenth", "sixteenth", "seventeenth", "eighteenth", "nineteenth"])]),
    dict(day=39, act=4, theme="序数收尾",
         sent=["twenty-first", "twenty-fifth", "thirty-first", "about", "almost", "nearly", "per", "total"],
         ext=[("大序数（锚词：twenty-first）", "twenty-first",
               ["twenty-second", "twenty-third", "twenty-fourth", "twenty-sixth", "twenty-seventh", "twenty-eighth",
                "twenty-ninth", "thirtieth"])]),
    dict(day=40, act=4, theme="方位介词",
         sent=["across", "along", "through", "past", "over", "under", "left", "right"],
         ext=[("位置介词（锚词：left）", "left", ["behind", "beside", "between", "above", "below"])]),
]
