# 第 3 幕（Day 21-30）：新朋友与日常。语法：现在进行时、情态动词 can/could/must/have to。
DAYS = [
    dict(day=21, act=3, theme="此刻正在进行",
         sent=["look", "listen", "read", "write", "sit", "stand", "walk", "watch", "see", "make"],
         ext=[("look 短语家族（锚词：look）", "look", ["look at", "look for", "look out", "look after"]),
              ("listen 短语（锚词：listen）", "listen", ["listen to"])]),
    dict(day=22, act=3, theme="球类运动",
         sent=["sport", "football", "basketball", "volleyball", "table-tennis", "tennis", "badminton", "baseball", "match", "team", "player", "ball", "club"],
         ext=[("球类补充（锚词：football）", "football", ["golf", "hockey", "bat", "racket"])]),
    dict(day=23, act=3, theme="我会做的事",
         sent=["can", "could", "swim", "dance", "sing", "draw", "ride", "jump", "kick", "throw", "climb"],
         ext=[("艺术表演者（锚词：dance）", "dance", ["dancer", "singer", "artist"])]),
    dict(day=24, act=3, theme="校园规则",
         sent=["must", "have to", "should", "hurry", "wait", "stop", "careful", "quiet", "slow", "fast", "early", "late"],
         ext=[("方式副词（锚词：careful）", "careful", ["carefully", "quick", "quickly"])]),
    dict(day=25, act=3, theme="农场动物",
         sent=["animal", "bird", "fish", "mouse", "rabbit", "duck", "chicken", "cow", "horse", "farm", "farmer", "pet"],
         ext=[("动物补充（锚词：animal）", "animal", ["parrot", "bear", "camel"])]),
    dict(day=26, act=3, theme="动物园",
         sent=["zoo", "lion", "tiger", "elephant", "monkey", "snake", "dinosaur", "dolphin", "whale", "insect", "wild", "huge", "tiny"],
         ext=[("昆虫与飞虫（锚词：insect）", "insect", ["fly"])]),
    dict(day=27, act=3, theme="主食与调味",
         sent=["food", "bread", "rice", "noodles", "egg", "soup", "potato", "meat", "cheese", "butter"],
         ext=[("调味品（锚词：butter）", "butter", ["salt", "sugar", "oil", "pepper"])]),
    dict(day=28, act=3, theme="水果蔬菜",
         sent=["fruit", "apple", "banana", "orange", "grape", "strawberry", "mango", "lemon", "vegetable", "salad"],
         ext=[("更多果蔬（锚词：fruit）", "fruit", ["peach", "pear", "carrot", "onion"])]),
    dict(day=29, act=3, theme="饮料与点心",
         sent=["drink", "water", "milk", "juice", "tea", "coffee", "cola", "milkshake", "ice cream", "chocolate", "cake"],
         ext=[("甜味点心（锚词：cake）", "cake", ["biscuit", "sweet", "honey", "jam"])]),
    dict(day=30, act=3, theme="时间表达",
         sent=["o'clock", "half past", "quarter", "a.m.", "p.m.", "hour", "minute", "second", "moment", "time", "tonight", "tomorrow"],
         ext=[("一天中的时刻（锚词：time）", "time", ["midnight", "noon"])]),
]
