# 第 9 幕（Day 81-90）：一月末，返校与梦想。语法：状语从句 because/when/if、宾语从句。
DAYS = [
    dict(day=81, act=9, theme="考试周",
         sent=["exam", "test", "quiz", "practice", "practise", "study", "improve", "mistake", "fail", "pass", "homework", "ready", "useful", "reading", "pencil case"],
         ext=[("教与学（锚词：study）", "study", ["teach", "student"])]),
    dict(day=82, act=9, theme="because 从句",
         sent=["agree", "against", "among", "ask", "describe", "explain", "difference", "different", "example", "activity", "else", "anyway", "excuse"],
         ext=[("说明与信息（锚词：explain）", "explain", ["instructions", "information"])]),
    dict(day=83, act=9, theme="when/while/until 从句",
         sent=["while", "until", "till", "afternoon", "evening", "night", "day", "afterwards", "later", "weekly", "monthly", "moon", "well", "suddenly"],
         ext=[("时间反义复习（锚词：later）", "later",
               [{"rev": "early", "from": 24}, {"rev": "late", "from": 24}, {"rev": "soon", "from": 16}])]),
    dict(day=84, act=9, theme="if 条件句",
         sent=["if", "or", "any", "some", "other", "another", "such", "all right", "at all", "without", "except", "yes", "next"],
         ext=[]),
    dict(day=85, act=9, theme="转述与通信",
         sent=["sound", "hear", "matter", "mind", "true", "story", "note", "chat", "chatroom", "pen-friend", "heart", "her", "his", "its"],
         ext=[("通信与记录（锚词：chat）", "chat",
               [{"rev": "email", "from": 78}, {"rev": "letter", "from": 57}, {"rev": "postcard", "from": 57}, "write down"])]),
    dict(day=86, act=9, theme="学校演出",
         sent=["stage", "show", "act", "actor", "clown", "circus", "dancing", "picture", "drawing", "paint", "king", "queen", "dragon", "Miss", "Ms"],
         ext=[("影像（锚词：paint）", "paint", ["camera", "photography", "photo"])]),
    dict(day=87, act=9, theme="汽车与道路",
         sent=["brake", "tyre", "wheel", "engine", "driving licence", "parking", "garage", "petrol", "petrol station", "motorway", "licence", "cycle"],
         ext=[("形状与线（锚词：wheel）", "wheel", ["round", "circle", "triangle", "dot", "line"]),
              ("道路设施（锚词：motorway）", "motorway", ["traffic lights"])]),
    dict(day=88, act=9, theme="开关与上下",
         sent=["get on", "get off", "take off", "turn on", "turn off", "shut", "exit", "enter", "entrance", "sit down", "wake up", "go out"],
         ext=[("开关反义复习（锚词：shut）", "shut", [{"rev": "close", "from": 5}, {"rev": "put on", "from": 34}])]),
    dict(day=89, act=9, theme="材质与时尚",
         sent=["fashion", "leather", "wool", "silver", "gold", "blonde", "plastic", "metal", "paper", "type", "soft", "hard", "brown", "boot", "shoe"],
         ext=[("衣物补充（锚词：fashion）", "fashion", ["uniform", "pyjamas", "trainers"])]),
    dict(day=90, act=9, theme="梦想未来",
         sent=["dream", "become", "grow up", "teenager", "college", "university", "diploma", "advanced", "level", "company", "would", "include"],
         ext=[("成功之路（锚词：dream）", "dream", ["success", "prize"])]),
]
