# 第 10 幕（Day 91-100）：二月，尾声与展望。语法：间接引语入门、综合复习。
DAYS = [
    dict(day=91, act=10, theme="度量衡",
         sent=["metre", "centimetre", "kilometre", "kilogram", "gram", "litre", "mile", "foot", "add", "half", "full of", "bit", "extra"],
         ext=[]),
    dict(day=92, act=10, theme="副词与功能词收尾",
         sent=["actually", "also", "as well", "away", "these", "those", "instead", "itself", "ourselves", "themselves", "herself", "himself", "yourself", "myself"],
         ext=[("也的家族（锚词：also）", "also", ["as well as", "at the same time"]),
              ("替代（锚词：instead）", "instead", ["instead of"])]),
    dict(day=93, act=10, theme="动作动词收尾",
         sent=["off", "keep", "let", "try", "start", "finish", "join", "follow", "rest", "move", "hit", "lie down", "catch"],
         ext=[("休息与停止（锚词：rest）", "rest", [{"rev": "stop", "from": 24}])]),
    dict(day=94, act=10, theme="居家收尾",
         sent=["carpet", "sheet", "board", "roof", "light", "living room", "sitting room", "dining room", "comfortable", "make up", "part", "pair"],
         ext=[]),
    dict(day=95, act=10, theme="自然与能源",
         sent=["island", "lake", "mountain", "space", "air", "alive", "season", "spring", "burn", "gas", "electric", "electricity", "nature", "east", "west"],
         ext=[("燃烧（锚词：burn）", "burn", ["smoke"])]),
    dict(day=96, act=10, theme="健康生活",
         sent=["exercise", "fit", "health", "sleep", "sleepy", "shoulder", "stomach", "laugh", "smile", "fishing", "riding", "skateboard", "sports centre"],
         ext=[("健身（锚词：exercise）", "exercise", ["get fit"])]),
    dict(day=97, act=10, theme="出行与邮政收尾",
         sent=["scooter", "passenger", "path", "way", "seat", "holidays", "rich", "poor", "same", "luck", "lucky", "run", "send"],
         ext=[("邮政（锚词：way）", "way", ["by post", {"rev": "postcard", "from": 57}, {"rev": "stamp", "from": 57}]),
              ("住宿（锚词：holidays）", "holidays", ["guest-house"])]),
    dict(day=98, act=10, theme="工作与商店收尾",
         sent=["earn", "rent", "working hours", "shopper", "department store", "department", "store", "closed", "build", "building", "business", "machine", "factory", "form"],
         ext=[("商店复习（锚词：store）", "store",
               [{"rev": "shop", "from": 6}, {"rev": "supermarket", "from": 6}, {"rev": "market", "from": 6}]),
              ("金钱复习（锚词：earn）", "earn",
               [{"rev": "money", "from": 35}, {"rev": "cash", "from": 36}, {"rev": "cheque", "from": 36},
                {"rev": "credit card", "from": 36}])]),
    dict(day=99, act=10, theme="综合复习 1：方位与杂项",
         sent=["front", "side", "end", "top", "bottom", "middle", "as", "steal", "busy", "pocket", "century", "north", "south"],
         ext=[("方位复习（锚词：front）", "front",
               [{"rev": "behind", "from": 40}, {"rev": "above", "from": 40}, {"rev": "below", "from": 40},
                {"rev": "left", "from": 40}, {"rev": "right", "from": 40}])]),
    dict(day=100, act=10, theme="综合复习 2：百天收官",
         sent=["OK", "able", "prefer", "exciting", "loud", "noisy", "slowly", "beginner", "variety", "canal", "left hand", "friend", "friendly"],
         ext=[]),
]
